#!/bin/sh
#
#  Copyright 2019 DefKorns (https://gitlab.com/advokaten/remap-canoekachikachi/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source $mountpoint/etc/options_menu/input/scripts/om_vars
script_init

joystick="/dev/input/by-path/platform-twi.1-event-joystick"

buttonseletor() {
	buttons=$(cat $joystick | hexdump -v -e '1/1 "%02x"' -n 32)
	ctrl_db="/var/lib/hakchi/rootfs/gamecontrollerdb.txt"
	case "${buttons:20:4}" in
	3001)
		btn="b1"
		;;
	3101)
		btn="b0"
		;;
	3301)
		btn="b2"
		;;
	3401)
		btn="b3"
		;;
	c202)
		btn="b13"
		;;
	c302)
		btn="b14"
		;;
	c002)
		btn="b11"
		;;
	c102)
		btn="b12"
		;;
	0200)
		btn="b4"
		;;
	3601)
		btn="a2"
		;;
	3801)
		btn="b7"
		;;
	0500)
		btn="b5"
		;;
	3701)
		btn="a5"
		;;
	3901)
		btn="b7"
		;;
	3a01)
		btn="b9"
		;;
	3b01)
		btn="b9"
		;;
	3c01)
		btn="b10"
		;;
	0000)
		btn="a0"
		;;
	0100)
		btn="a1"
		;;
	0300)
		btn="a3"
		;;
	0400)
		btn="a4"
		;;
	esac
	usleep 100000
}
while [ ! -e $joystick ]; do usleep 100; done
echo "press UP"
buttonseletor
sed -r -i "s/UP/${btn}/g;" $ctrl_db
echo "press DOWN"
buttonseletor
sed -r -i "s/DOWN/${btn}/g;" $ctrl_db
echo "press LEFT"
buttonseletor
sed -r -i "s/LEFT/${btn}/g;" $ctrl_db
echo "press RIGHT"
buttonseletor
sed -r -i "s/RIGHT/${btn}/g;" $ctrl_db
echo "press A"
buttonseletor
ok="$btn"
sed -r -i "s/CIRCLE/${btn}/g;" $ctrl_db
echo "press B"
buttonseletor
sed -r -i "s/EXE/${btn}/g;" $ctrl_db
echo "press X"
buttonseletor
sed -r -i "s/TRIANGLE/${btn}/g;" $ctrl_db
echo "press Y"
buttonseletor
sed -r -i "s/SQUARE/${btn}/g;" $ctrl_db
echo "press SELECT"
buttonseletor
sed -r -i "s/SELECT/${btn}/g;" $ctrl_db
echo "press START"
buttonseletor
sed -r -i "s/START/${btn}/g;" $ctrl_db
echo "press L1"
buttonseletor
sed -r -i "s/L1/${btn}/g;" $ctrl_db
echo "press R1"
buttonseletor
sed -r -i "s/R1/${btn}/g;" $ctrl_db
echo "press L1 LONG"
buttonseletor
sed -r -i "s/L3/${btn}/g;" $ctrl_db
echo "press R1 LONG"
buttonseletor
sed -r -i "s/R3/${btn}/g;" $ctrl_db

echo "Do you have more buttons to configure?
Press A to continue.
Any other key to cancel"
buttonseletor
if [ "$btn" == "$ok" ]; then
	echo "press HOME"
	buttonseletor
	sed -r -i "s/HOME/${btn}/g;" $ctrl_db
	echo "press L2"
	buttonseletor
	sed -r -i "s/L2/${btn}/g;" $ctrl_db
	echo "press R2"
	buttonseletor
	sed -r -i "s/R2/${btn}/g;" $ctrl_db
	echo "Press Left Analog X"
	buttonseletor
	sed -r -i "s/LX/${btn}/g;" $ctrl_db
	echo "Press Left Analog Y"
	buttonseletor
	sed -r -i "s/LY/${btn}/g;" $ctrl_db
	echo "Press Right Analog X"
	buttonseletor
	sed -r -i "s/RX/${btn}/g;" $ctrl_db
	echo "Press Right Analog Y"
	buttonseletor
	sed -r -i "s/RY/${btn}/g;" $ctrl_db
else
	sed -r -i 's/LX/a0/g;' $ctrl_db
	sed -r -i 's/LY/a1/g;' $ctrl_db
	sed -r -i 's/RX/a3/g;' $ctrl_db
	sed -r -i 's/RY/a4/g;' $ctrl_db
	sed -r -i 's/HOME/b10/g;' $ctrl_db
	sed -r -i 's/L2/b6/g;' $ctrl_db
	sed -r -i 's/R2/b7/g;' $ctrl_db
fi
