#!/bin/sh
#
#  Copyright 2019 DefKorns (https://github.com/DefKorns/om-remap-canoekachikachi/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

sdl2path0="$mountpoint/etc/sdl2"
sdl2path1="$mountpoint/etc/options_menu/inputs/assets/sdl2"

mount_bind "$sdl2path1" "$sdl2path0" 

unset sdl2path0
unset sdl2path1

