#!/bin/sh
#
#  Copyright 2019 DefKorns (https://gitlab.com/advokaten/remap-canoekachikachi/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source $mountpoint/etc/options_menu/inputs/scripts/om_vars
script_init
# Restore default input for all users.
if [ -f "$omModScripts/om_defaultDb.txt" ]; then
  cp $omModScripts/om_defaultDb.txt /etc/options_menu/input/gamecontrollerdb.txt
  echo "Inputs reset to default."
else
  echo "Error!"
  echo "Unable to locate default config."
fi