#!/bin/sh

start() {
  /etc/options_menu/inputs/pad_mapper >/dev/null 2>&1 &
}

stop() {
  killall pad_mapper 2>/dev/null
}

case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
restart)
  stop
  start
  ;;
*)
  echo "pad_mapper: use start, stop or restart."
  exit 1
  ;;
esac
