#!/bin/sh
# shellcheck disable=SC2154
#
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

killall pad_mapper 2>/dev/null
rm -f /tmp/pad_mapper.pause

sdl_dir="/etc/sdl2"
sdl_db="$sdl_dir/gamecontrollerdb.txt"

while grep -qE " ($sdl_db|$sdl_dir) " /proc/mounts; do
  umount "$sdl_db" 2>/dev/null || umount "$sdl_dir" 2>/dev/null || break
done

rm -f "$rootfs/etc/preinit.d/p8000_gamepadremapper"
rm -rf "$rootfs/etc/options_menu/inputs"
